name: CI/CD for System Game

on:
  push:
    branches: [ "release","master" ]
  pull_request:
    branches: [ "release","master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Test
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Deploy to Production
        run: ./gradlew publish

# Add additional steps for deployment to specific platforms (iOS, Android, etc.) if needed
